version: '3'

name: 'mooshak:1.0'
services:
  mooshak:
    build:
      context: ./mooshak
      network: host
    container_name: mooshak_sshd
    tty: true
    restart: always
    volumes:
      - mooshak_sshd:/etc/ssh
    ports:
      - 2255:22
    networks:
      - mooshak

  wstunnel:
    build:
      context: ./wstunnel
      network: host
    ports:
      - 3344:80
    depends_on:
      - mooshak
    networks:
      - mooshak


volumes:
  mooshak_sshd:
    external: true

networks:
  mooshak:
    external: true
