baseURL = 'https://sepgh.github.io/mooshak/'
languageCode = 'en-us'
title = 'Mooshak'
enableGitInfo = true
disableKinds = ['taxonomy', 'taxonomyTerm']
relativeURLs = true
canonifyURLs = true
googleAnalytics = "G-4QMM7C7BZL"

[module]
[[module.imports]]
path = 'github.com/alex-shpak/hugo-book'

[params]
    BookTheme = 'auto'
    BookToC = true
    BookMenuBundle = "/menu"
    BookCommitPath = 'commit'
    BookDateFormat = 'Jan 2, 2006'
